# fly.toml app configuration file generated for utility on 2023-05-30T11:38:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elixirstream"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"
processes = []

[deploy]
  release_command = "/app/bin/utility eval 'Utility.Release.migrate()'"

[env]
  ECTO_IPV6 = "true"
  PORT = "4000"
  STORAGE_DIR = "/storage/utility"

[experimental]
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []
  private_network = true

[[mounts]]
  destination = "/storage"
  encrypted = false
  processes = []
  source = "elixirstream_data"

[[services]]
  http_checks = []
  internal_port = 4000
  processes = []
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
